### PR TITLE
Add itikz

### PR DESCRIPTION
**Pull request by jbn**
[itikz](https://github.com/jbn/itikz)

Cell and line magic for PGF/TikZ-to-SVG rendering in Jupyter notebooks.

### CODE REVIEW

**Comment by xiaohanyu** [comment]
Is this production ready?

**Comment by jbn** [comment]
I was going to say yes, but then just noticed an introduced bug from yesterdays debugging artifacts. 

I'm using it daily right now to craft my dissertation figures. It works; it's useful. 

But, I'll circle back in a week or two after a `0.1.0` release with better (any) testing, and django templating.

**Comment by xiaohanyu** [comment]
Thanks!

**Comment by jbn** [comment]
Just bumped to the first minor version with 100% coverage!

I also couldn't find you on twitter, but [mentioned this repo in a release announcement thread](https://twitter.com/generativist/status/1054075410722385925).

Cheers!

**Pull request merged**
